# Generated by Django 5.0.4 on 2024-07-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avina', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='a@b.com', max_length=254),
        ),
    ]
