# Generated by Django 5.0.4 on 2024-07-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avina', '0013_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
