# Generated by Django 5.0.4 on 2024-07-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avina', '0006_alter_comment_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
