# Generated by Django 5.0.4 on 2024-07-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avina', '0004_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
