# Generated by Django 5.0.4 on 2024-07-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avina', '0010_remove_comment_extra_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
