# Generated by Django 5.0.4 on 2024-07-23 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avina', '0011_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
